# Generated by Django 4.2.1 on 2023-06-04 16:51

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=order.models.generate_order_id, editable=False, max_length=150
            ),
        ),
    ]
