# Generated by Django 4.2.1 on 2023-06-02 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("image", models.URLField()),
                ("price", models.FloatField()),
                ("rating", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
